// src/schema.ts

// Re-export all Better Auth tables generated by the CLI.
// This makes Drizzle aware of them so migrations can be generated.
export * from "../auth-schema";

// ------------------------------------------------------------
// Add your own application tables below (optional)
// ------------------------------------------------------------

// Example custom table (remove if not needed)
import { pgTable, text, timestamp } from "drizzle-orm/pg-core";

export const exampleTable = pgTable("example_table", {
  id: text("id").primaryKey(),
  name: text("nombre").notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});
